# Generated by Django 5.2.8 on 2025-11-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(default='NSW', max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('property_type', models.CharField(choices=[('office', 'Office'), ('retail', 'Retail'), ('industrial', 'Industrial')], max_length=20)),
                ('size_sqm', models.IntegerField()),
                ('annual_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
